service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  loaderio-4fec6a95acf27bc0791897740bd2057e:
    handler: handler.handler
    events:
      - http:
          method: get
          path: /
  
  insertPeople:
    handler: handler.handler
    events:
      - http:
          method: get
          path: /insertPeople

  insertVehicle:
    handler: handler.handler
    events:
      - http:
          method: get
          path: /insertVehicle
  
  getUserAndVehicle:
    handler: handler.handler
    events:
      - http:
          method: get
          path: /query
